[phases.setup]
# add any extra packages if needed

[phases.build]
commands = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "php artisan key:generate --ansi || true",
  "php artisan storage:link || true",
  "if [ -f package.json ]; then npm ci --silent && npm run production || true; fi"
]

[phases.start]
command = "bash start.sh"